services:

  backend:
    image: node:20-alpine
    container_name: backend
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./app-crm/backend:/app
      - /app/node_modules
      - ./data-lake:/data-lake
    ports:
      - "4000:4000"
    environment:
      MONGO_URI: 
      JWT_SECRET: change_me_with_a_long_random_secret
      PORT: 4000
      NODE_ENV: development
      OCR_API_URL: http://ocr-api:8000
      DATA_LAKE_RAW: /data-lake/raw
    command: sh -c "npm install && npm run dev"

  ocr-api:
    build:
      context: ./ml-ocr-engine
    container_name: ocr-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./data-lake:/data-lake
    environment:
      DATA_LAKE_CLEAN: /data-lake/clean
      DATA_LAKE_CURATED: /data-lake/curated

  app-crm-frontend:
    image: node:18-alpine
    container_name: idp_crm_frontend
    working_dir: /app/frontend
    volumes:
      - ./app-crm/frontend:/app/frontend
    command: sh -c "npm install && npm start"
    ports:
      - "3010:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - REACT_APP_API_URL=http://localhost:4000/api
      - HOST=0.0.0.0

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    command: server /data --console-address ":9001"

  minio-init:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      mc alias set myminio http://minio:9000 admin password123;
      mc mb myminio/document-datalake;
      exit 0;
      "