services:

  backend:
    image: node:20-alpine
    container_name: backend
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./app-crm/backend:/app
      - /app/node_modules
    ports:
      - "4000:4000"
    environment:
      MONGO_URI: mongodb+srv://hackathon_db_user:5WIN4zcudKJAunn0@cluster0.ptkiqp9.mongodb.net/
      JWT_SECRET: change_me_with_a_long_random_secret
      PORT: 4000
      NODE_ENV: development
      OCR_API_URL: http://ocr-api:8000
    command: sh -c "npm install && npm run dev"

  ocr-api:
    build:
      context: ./ml-ocr-engine
    container_name: ocr-api
    restart: unless-stopped
    ports:
      - "8000:8000"

  app-crm-frontend:
    image: node:18-alpine
    container_name: idp_crm_frontend
    working_dir: /app/frontend
    volumes:
      - ./app-crm/frontend:/app/frontend
    command: sh -c "npm install && npm start"
    ports:
      - "3010:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - REACT_APP_API_URL=http://localhost:4000/api
